namespace: sample
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
namePrefix: prod-
commonLabels:
  env: prod
patches:
  - path: deployment.yaml
  - path: ingress.yaml
  - path: service.yaml