apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  # To use k8s health-check service(/healthz), k8s private network should be registered.
  ALLOWED_HOSTS: '["localhost", "127.0.0.1", "*"]'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-django
  template:
    metadata:
      labels:
        app: k8s-django
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - name: k8s-django
          image: elhongsh/k8s-django:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Adjust to match the containerPort
            initialDelaySeconds: 5 # Wait 5 seconds after the container starts
            periodSeconds: 5 # Check readiness every 5 seconds